$(function(){
	$("#heatli").click(function(){
		$("#heat").show("slow");
		$("#heat").siblings().hide();
	})
})
$(function(){
	$("#cava").click(function(){
		$("#initial").show("slow");
		$("#initial").siblings().hide();
	})
})
$(function(){
	$("#bcava").click(function(){
		$("#bcavaliers").show("slow");
		$("#bcavaliers").siblings().hide();
	})
})
$(function(){
	$("#laker").click(function(){
		$("#lakers").show("slow");
		$("#lakers").siblings().hide();
	})
})
/*$("#id").siblings()当前元素的所有兄弟节点*/